name: macOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4


    - name: Get Submodules
      run: ./get_dlc

    - name: Compile Shader
      working-directory: Shader
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check Shader
      working-directory: Shader
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  Shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Shader image
        path: Shader/Deployment/test.png
    - name: Compile Texture
      working-directory: Texture
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check Texture
      working-directory: Texture
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  Texture failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Texture image
        path: Texture/Deployment/test.png
    - name: Compile ComputeShader
      working-directory: ComputeShader
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check ComputeShader
      working-directory: ComputeShader
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  ComputeShader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ComputeShader image
        path: ComputeShader/Deployment/test.png
    - name: Compile TextureArray
      working-directory: TextureArray
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check TextureArray
      working-directory: TextureArray
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  TextureArray failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: TextureArray image
        path: TextureArray/Deployment/test.png
    - name: Compile Raytracing
      working-directory: Raytracing
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check Raytracing
      working-directory: Raytracing
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  Raytracing failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Raytracing image
        path: Raytracing/Deployment/test.png
    - name: Compile Bindless
      working-directory: Bindless
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check Bindless
      working-directory: Bindless
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  Bindless failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Bindless image
        path: Bindless/Deployment/test.png
    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 00_empty
      working-directory: 00_empty
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/Deployment/test.png
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/Deployment/test.png
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/Deployment/test.png
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/Deployment/test.png
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 04_textured_cube
      working-directory: 04_textured_cube
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  04_textured_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 04_textured_cube image
        path: 04_textured_cube/Deployment/test.png
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 05_camera_controls
      working-directory: 05_camera_controls
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  05_camera_controls failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 05_camera_controls image
        path: 05_camera_controls/Deployment/test.png
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 06_render_targets
      working-directory: 06_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  06_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 06_render_targets image
        path: 06_render_targets/Deployment/test.png
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  07_multiple_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 07_multiple_render_targets image
        path: 07_multiple_render_targets/Deployment/test.png
    - name: Compile 08_float_render_targets
      working-directory: 08_float_render_targets
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 08_float_render_targets
      working-directory: 08_float_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  08_float_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 08_float_render_targets image
        path: 08_float_render_targets/Deployment/test.png
    - name: Compile 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  09_depth_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 09_depth_render_targets image
        path: 09_depth_render_targets/Deployment/test.png
    - name: Compile 10_cubemap
      working-directory: 10_cubemap
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 10_cubemap
      working-directory: 10_cubemap
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  10_cubemap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 10_cubemap image
        path: 10_cubemap/Deployment/test.png
    - name: Compile 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  11_instanced_rendering failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 11_instanced_rendering image
        path: 11_instanced_rendering/Deployment/test.png
    - name: Compile 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  12_set_render_target_depth failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 12_set_render_target_depth image
        path: 12_set_render_target_depth/Deployment/test.png
    - name: Compile 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  13_generate_mipmaps failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 13_generate_mipmaps image
        path: 13_generate_mipmaps/Deployment/test.png
    - name: Compile 14_set_mipmap
      working-directory: 14_set_mipmap
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 14_set_mipmap
      working-directory: 14_set_mipmap
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  14_set_mipmap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 14_set_mipmap image
        path: 14_set_mipmap/Deployment/test.png
    - name: Compile 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: ../Kinc/make osx -g metal --option screenshot --debug --run
    - name: Check 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  15_deinterleaved_buffers failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 15_deinterleaved_buffers image
        path: 15_deinterleaved_buffers/Deployment/test.png
